### ISSUE TITLE
CalendarbookingService causes App Crash on Android Platform

### ISSUE THREAD

**Issue by speciosus** [liferay/liferay-mobile-sdk#13]
I want to report a bug related to the use of CalendarbookingService on android platform.
Specifically, the invocation of the "search" function causes a crash of the application that you can not manage even with a try-catch block.
An example of invocation is the following:
<code>
CalendarbookingService calendarbookingService = new CalendarbookingService(session);

                long companyId = 10157;

                JSONArray groupIdArray = new JSONArray();
                groupIdArray.put(13601);

                JSONArray calendarIds = new JSONArray();
                calendarIds.put(13904);

                JSONArray calendarResIdArray = new JSONArray();
                calendarResIdArray.put(13630);

                JSONArray statuses = new JSONArray();
                statuses.put(0);

                JSONArray last = calendarbookingService.search(companyId, groupIdArray, calendarIds, calendarResIdArray, -1l , null, startTime, endTime, true, statuses, -1, -1, null);
</code>

The same code runs without problems on the iOs platform.

Thanks in advance for the help .

**Comment by brunofarache** [comment]
Which version are you using and which error are you getting on the logs?

**Comment by speciosus** [comment]
I'm using the latest version of SDK (6.2.0.9) and I get a "RuntimeException" thats kills the app even if the code is surrounded by a try-catch block that catch "Exception"

**Comment by brunofarache** [comment]
Can you catch the RuntimeException to see what's wrong? In Android, when they are not caught, they also show up in the console.

**Comment by speciosus** [comment]
"RuntimeException" is subclass of "Exception" but it fails to manage it.
As you can see in the screenshot, the detail of exception is void while running in debug mode.

![bug](https://cloud.githubusercontent.com/assets/6883979/5899944/280b2c2a-a563-11e4-85f4-916ba7f86028.jpg)

**Comment by brunofarache** [comment]
Ah, maybe if you were catching Throwable instead it would catch it?

Anyways, there's a newer version of the Android SDK that fixes an issue that maybe related to yours (issue #9). I have published it to Maven but I guess you adding the .jar manually, I have also added it to the releases page:

https://github.com/liferay/liferay-mobile-sdk/releases/tag/android-6.2.0.14

**Comment by brunofarache** [comment]
You are using services that your generated yourself, right? You should also re-generate with the latest builder, because issue #9 also changes the way services are generated.

**Comment by speciosus** [comment]
Yes, I made a custom service.
I regenerated the services using the latest SDK: now the catch-block works as it should but catch (or throw) a void Exception (null).
In the debugger I can't see nothing interesting.

**Comment by speciosus** [comment]
I made some changes in my code with an explicit declaration of long type:

<code>
                long companyId = 10157l;

                JSONArray groupIdArray = new JSONArray();
                groupIdArray.put(13601l);

                JSONArray calendarIds = new JSONArray();
                calendarIds.put(13904l);

                JSONArray calendarResIdArray = new JSONArray();
                calendarResIdArray.put(13630l);

                JSONArray statuses = new JSONArray();
                statuses.put(0l);

                JSONArray last = calendarbookingService.search(companyId, groupIdArray, calendarIds, calendarResIdArray, -1l , null, startTime, endTime, true, statuses, -1, -1, null);
</code>

Now, I'm getting a detail exception:

"com.liferay.mobile.android.exception.ServerException: No JSON web service action with path /calendar-portlet/calendarbooking/search and method null for /"

**Comment by speciosus** [comment]
I solved the issue. The function search doesn't support "null" as value for keyword.
<code>
JSONArray last = calendarbookingService.search(companyId, groupIdArray, calendarIds, calendarResIdArray, -1l , "", startTime, endTime, true, statuses, -1, -1, null);
</code>

**Comment by brunofarache** [comment]
I see, that error means the server can't infer which method you are trying to call.
