### ISSUE TITLE
  SSL Cerificate Validation issue

### ISSUE THREAD

**Issue by chetan-AD** [liferay/liferay-mobile-sdk#17]
On iOS devices we are able to communicate we our SSL enabled server. but on android it throws javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException:.

So till certification issue get fixed do we have any method in liferay sdk to ignore this Validation issue at android mobile end.

**Comment by brunofarache** [comment]
Android doesn't allow self-signed certificates or there's something wrong with your certificate, see the documentation:

[https://developer.android.com/training/articles/security-ssl.html#CommonProblems](https://developer.android.com/training/articles/security-ssl.html#CommonProblems)
