### ISSUE TITLE
Error Message when running Liferay iOS SDK in Xcode, Version  6.2.0.21

### ISSUE THREAD

**Issue by Nishi-Fertig-Aus** [liferay/liferay-mobile-sdk#18]
Hello Bruno, I get an error message. Can you help me?

![2015-09-25 10 24 19 am](https://cloud.githubusercontent.com/assets/14584718/10096308/c249f1f6-6370-11e5-9073-dcb8b7c7423a.png)
![2015-09-25 10 25 13 am](https://cloud.githubusercontent.com/assets/14584718/10096313/cab6305c-6370-11e5-9c65-ebb92464ac47.png)

**Comment by brunofarache** [comment]
@Nishi-Fertig-Aus: it says LRUploadData.h wasn't found, which means that file is missing.

**Comment by Nishi-Fertig-Aus** [comment]
Hi Bruno, thank you for your response. I'm new to iOS and objective C. I just added the http folder to the project. The missing file is under http/File folder. But the error still shows up.

**Comment by brunofarache** [comment]
Why haven't you imported the whole Mobile SDK to your project?

**Comment by Nishi-Fertig-Aus** [comment]
Thank you. That solved the issue on a magical way.
