### ISSUE TITLE
CocoaPods just installs version 6.2.0.4 and not the latest. 

### ISSUE THREAD

**Issue by Nishi-Fertig-Aus** [liferay/liferay-mobile-sdk#19]
Hello Bruno,

I tried it several times and the log sometimes starts to download the latest sdk version, but then it falls back and starts installing the 6.2.0.4 version. Last time I closed all the Development Evironments on my computer and did use CocoaPods again and it just downladed the 6.2.0.4 version directly. Can you help? If I install it manually the AFNetworking Version 2.5.3 throws several errors.

![2015-10-06 01 35 54 pm](https://cloud.githubusercontent.com/assets/14584718/10307426/35aafbc4-6c2f-11e5-92ce-6f7e426fee27.png)

**Comment by brunofarache** [comment]
Maybe because you're specifying 6.2.0.4 in your Podfile?

**Comment by Nishi-Fertig-Aus** [comment]
No I did not specify the version. I created a cordova project and added ios to it. I moved to the platform/ios folder. There I created the Podfile with the single line. When I run $ pod install  it always downloads the 6.2.0.4 version.

**Comment by brunofarache** [comment]
What you are saying doesn't make much sense, @Nishi-Fertig-Aus. I recommend you looking at the Cocoapods documentation to see how to install pods to your project.

**Comment by Nishi-Fertig-Aus** [comment]
Hi Bruno,

Thank you for the Hint. When I added in Podfile the version 6.2.0.21. The CocoaPod gave me the hint, that there is the wrong build target. Yes indeed, cordova creates the project with iOS 6 as default target. After changing to iOS 9 the pod install command installs the latest version. Unfortunately there is a new issue if I run the project in xcode. Can you help?
![2015-10-06 05 38 54 pm](https://cloud.githubusercontent.com/assets/14584718/10313671/2277b980-6c51-11e5-9572-4922accc9ace.png)
