### ISSUE TITLE
Android Push: Add a method to Push.java to unregister a push passing the context and senderId

### ISSUE THREAD

**Issue by denissignoretto** [liferay/liferay-mobile-sdk#21]
Like it happen for registration, create unregister overloaded method that allow push unregistration passing context and senderId as parameters: 

e.g. Push.with(session).unregister(this, SENDER_ID);

**Comment by nhpatt** [comment]
Mmm... is it enough with the currently existing one: public void unregister(String registrationId) throws Exception ?
