### ISSUE TITLE
Version number iTunes issue

### ISSUE THREAD

**Issue by asotog** [liferay/liferay-mobile-sdk#22]
Hi there,

We are having version number complain from iTunes when trying to release application using Liferay Mobile SDK, we are using cocoapods, please check screen shot attached, it complains about the version number format:

<img width="789" alt="screen shot 2016-01-25 at 3 57 09 pm" src="https://cloud.githubusercontent.com/assets/813023/12565878/5406164a-c37c-11e5-888c-ded45fac74a2.png">

i noticed that you haven't changed yet the code in podspec from repository:
Pod::Spec.new do |s|
	s.name					= "Liferay-iOS-SDK"
	s.module_name			= "LRMobileSDK"
	s.version				= "6.2.0.22"

**Comment by brunofarache** [comment]
Hey @asotog,

We are going to fix that on next release. For now you can manually set the version to something that has 2 dots instead of 3. Search for the Mobile SDK's Info.plist in Xcode and change that before archiving.

**Comment by asotog** [comment]
Thanks we did that to solve the issue meanwhile
