### ISSUE TITLE
Portlet Configuration Page Missing on Liferay CE 7.0.1

### ISSUE THREAD

**Issue by phancox** [liferay/liferay-mobile-sdk#31]
The Push Notification Portlet only shows "Devices" and "Test" tabs on Liferay CE 7.0.1  There is no configuration tab visible.

**Comment by nhpatt** [comment]
The configuration tab is now a system setting and you can set it from there.

**Comment by brunofarache** [comment]
Reopening issue because we need to add that to the documentation.

thanks for the heads up @phancox!

**Comment by phancox** [comment]
Thanks guys.
