### ISSUE TITLE
Code=500 "http-error" UserInfo={NSLocalizedDescription=http-error}

### ISSUE THREAD

**Issue by MoathOthman** [liferay/liferay-mobile-sdk#33]
Hi , I've been trying to to apply the instructions in this tutorial 
https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/using-screenlets-in-ios-apps
I did exactly the same  but I get this error . 
**Error Domain=com.liferay.mobile.sdk Code=500 "http-error" UserInfo={NSLocalizedDescription=http-error}** 

Environment
- xcode 7.3.1 , OS X 10.11.5

**Comment by brunofarache** [comment]
This is the Mobile SDK repo, not Liferay Screens, which can be found here:
https://github.com/liferay/liferay-screens
