### ISSUE TITLE
add a sample app with swift

### ISSUE THREAD

**Issue by nhatchu** [liferay/liferay-mobile-sdk#35]
Hi,

Could you provide a sample app with swift?

Regards Nhat Chu

**Comment by victorlaerte** [comment]
Hi @nhatchu have you heard about Liferay Screens? It's built with Swift using Mobile SDK. 

[Liferay Screens](https://github.com/liferay/liferay-screens)

[Example service using Mobile-SDK](https://github.com/liferay/liferay-screens/blob/develop/ios/Framework/Core/Auth/Common/Connectors/GetUserByEmailLiferayConnectors.swift)

If you need some help, let met know.
