### ISSUE TITLE
Is Xamarin package support on the project's roadmap?

### ISSUE THREAD

**Issue by dodikk** [liferay/liferay-mobile-sdk#37]
In case xamarin bindings do exist already, it would be nice to have a link in a readme.
If not, are you planning to build them?

**Comment by brunofarache** [comment]
We don't have support to Xamarin yet. We will research and check how easy would be to create a binding for Android/iOS.

**Comment by yuchi** [comment]
You can use this one made by @Ithildir: https://github.com/Ithildir/liferay-sdk-builder-windows
It hasn’t been updated for a while but should be _that_ hard to upgrade to the latest generator.

**Comment by dodikk** [comment]
>> You can use this one made by @Ithildir:

Thank you. According to the readme, it does not seem to support iOS or Android. However, actually, it's a PCL and it should work on mentioned platforms.

P.S. Not sure if `LGPL` license is permissive enough for applying this package on iOS due to AOT compilation and possible static linking.

**Comment by dodikk** [comment]
> This consists of a Portable Class Library 

Sorry, the readme does mention the PCL.
