### ISSUE TITLE
Getting error While uploading image

### ISSUE THREAD

**Issue by girijeshkumar2007** [liferay/liferay-mobile-sdk#49]
- (NSString *)addLocationWithUserId:(NSString *)userId title:(NSString *)title street:(NSString *)street city:(NSString *)city state:(NSString *)state zip:(NSString *)zip country:(NSString *)country latitude:(NSString *)latitude longitude:(NSString *)longitude image:(LRUploadData *)image keepPrivate:(BOOL)keepPrivate isVenue:(BOOL)isVenue isPermitRequired:(BOOL)isPermitRequired externalURL:(NSString *)externalURL tags:(NSArray *)tags collectionIds:(NSArray *)collectionIds error:(NSError **)error {
	NSMutableDictionary *_params = [NSMutableDictionary dictionaryWithDictionary:@{
		@"userId": [self checkNull: userId],
		@"title": [self checkNull: title],
		@"street": [self checkNull: street],
		@"city": [self checkNull: city],
		@"state": [self checkNull: state],
		@"zip": [self checkNull: zip],
		@"country": [self checkNull: country],
		@"latitude": [self checkNull: latitude],
		@"longitude": [self checkNull: longitude],
		@"image": [self checkNull: image],
		@"keepPrivate": @(keepPrivate),
		@"isVenue": @(isVenue),
		@"isPermitRequired": @(isPermitRequired),
		@"externalURL": [self checkNull: externalURL],
		@"tags": [self checkNull: tags],
		@"collectionIds": [self checkNull: collectionIds]
	}];

	NSDictionary *_command = @{@"/scoutt-portlet.location/add-location": _params};

	return (NSString *)[self.session upload:_command error:error];
}
Response
Printing description of responseObject:
{
    exception = "java.lang.RuntimeException";
    message = "No JSON web service action associated with path /location/add-location and method POST for //scoutt-portlet";
}

**Comment by victorlaerte** [comment]
Did you try same request using curl or postman? By this msg error is difficult to related this issue to Mobile SDK

**Comment by girijeshkumar2007** [comment]
i manage to fix this issue by using AFNetwroking libaray thanks
