### ISSUE TITLE
IPv6 problem

### ISSUE THREAD

**Issue by fabioalmeidaxpand** [liferay/liferay-mobile-sdk#67]
Hello,

I'm using 7.0.7 version of liferay-mobile-sdk, and I'm having my application rejected by the Apple Store, because of a IPv6 issue. They claim that they are not able to run my application on a Wi-Fi connected to an IPv6 network. 
I'm only using the LiferaySDK to communicate with the server, does anyone had this issue too? Can be the AFNetworking version used by the LiferaySDK be the reason to this rejection?

Thanks in advance

**Comment by victorg1991** [comment]
Hi @fabioalmeidaxpand you can try to use the version 7.1 that comes with a new version of AFNetworking :)

**Comment by fabioalmeidaxpand** [comment]
Hello @victorg1991, thanks for the reply. Isn't the version 7.1 still in beta? I installed the version 7.1 once, for testing, and it was using the same AFNetworking version (2.6.3).

**Comment by victorg1991** [comment]
It's not in beta anymore, you can see the dependency [here](https://github.com/liferay/liferay-mobile-sdk/blob/master/Liferay-iOS-SDK.podspec#L30)

**Comment by fabioalmeidaxpand** [comment]
@victorg1991  I didn't notice that it's not beta anymore. I will test with the new version! Do you know if anyone was having the same problem about IPv6 with the 7.0.7 version?

**Comment by fabioalmeidaxpand** [comment]
@victorg1991 sorry to insist in this question. Do you know if anyone was having the same problem about IPv6 with the 7.0.7 version of liferay-mobile-sdk?

**Comment by allanragec** [comment]
@fabioalmeidaxpand In mobile sdk version 7.0.7 we were using AFNetworking version 2.6.3. We only start to use AFNetworking 3 in mobile-sdk 7.1
 
In AFNetworking 3.0+ has several fixes for IPV6 like https://github.com/AFNetworking/AFNetworking/pull/3174
you can see on release notes [release notes](https://github.com/AFNetworking/AFNetworking/releases/tag/3.0.0)

**Comment by victorg1991** [comment]
Sorry @fabioalmeidaxpand we are not aware of more people having this problem

**Comment by nhpatt** [comment]
I think it's safe to close it now, please reopen if necessary :)
