### ISSUE TITLE
Wrong package definition

### ISSUE THREAD

**Issue by sebastek** [liferay/liferay-mobile-sdk#75]
Hello

Is it expected that such class JournalArticleService.java declares 
package com.liferay.mobile.screens.service.v70
but is inside /com/liferay/mobile/android/v7/journalarticle folder ?

https://github.com/liferay/liferay-mobile-sdk/blob/master/android/services-v7/src/main/java/com/liferay/mobile/android/v7/journalarticle/JournalArticleService.java

Thanks
Sebastien

**Comment by nhpatt** [comment]
Yep, that's a mistake. I've moved to the right folder. Do you need a release? We'll do one at the end of April with all the adaptations for 7.2

**Comment by sebastek** [comment]
Thanks for the change. Release would perfect.

**Comment by nhpatt** [comment]
Done, it will be propagated in a few hours: https://bintray.com/liferay/liferay-mobile/liferay-android-services-v7/7.1.4
