### ISSUE TITLE
Error while getting console in Mac OS

### ISSUE THREAD

**Issue by chaitut715** [liferay/liferay-mobile-sdk#77]
$ ./gradlew createModule -P=all --stacktrace

> Task :createModule 
Error while getting console.

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

Mac OS 10.14.6

**Comment by nhpatt** [comment]
Hi!

It's explained [here](https://github.com/liferay/liferay-mobile-sdk/blob/master/builder/README.md)

> If you receive an "Error while getting console" message. Disable daemon mode:
> 
> ./gradlew createModule --no-daemon

**Comment by nhpatt** [comment]
Closing it, please reopen if the issue persists.
