### ISSUE TITLE
Liferay-iOS-SDK is not compatible  for AFNetworking v4

### ISSUE THREAD

**Issue by sheejasagar** [liferay/liferay-mobile-sdk#82]
Hi Team,

Liferay-iOS-SDK is not compatible  for AFNetworking v4. Could you please provide a version that supporting AFNetworking v4. 

Please find the below link for more details.

https://github.com/AFNetworking/AFNetworking/issues/4615

Thanks

**Comment by victorg1991** [comment]
Afnetworking has been updated in the 7.3.0 release :)

**Comment by sheejasagar** [comment]
Thanks Victor for the update. I will check it and let you know.

**Comment by sheejasagar** [comment]
Thanks Victor for the support. Its working fine.
